//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/inputSystems/Right Hand/rightHandActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RightHandActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RightHandActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""rightHandActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""95c429b5-196e-46f5-bcbf-6c4a94b55a5d"",
            ""actions"": [
                {
                    ""name"": ""GunOpen"",
                    ""type"": ""Button"",
                    ""id"": ""a20f03a5-3a91-4694-a506-6f53c4d15766"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootGun"",
                    ""type"": ""Button"",
                    ""id"": ""27fc731f-ac27-4283-b5a1-6de5586db226"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HandMove"",
                    ""type"": ""Value"",
                    ""id"": ""800f3031-c7ae-4d1e-ac99-5d30e4015f93"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""61de1212-53d1-4768-8794-7ef1a6e99dc9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""GunOpen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c3463f4-a2f3-4463-8404-8d5eacea4533"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""ShootGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""624e1089-61a6-4b65-883f-a4877214bc09"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ff828d96-9d1d-48ed-8bb9-6b8b1eb1c4a9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5cf019de-8085-4674-b84f-7ca301ad9e11"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""837351bf-8f0c-4030-b6a1-d56bc912dc99"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""054c7929-5d06-45ea-8e57-cc3b0f867766"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard"",
            ""bindingGroup"": ""keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_GunOpen = m_Gameplay.FindAction("GunOpen", throwIfNotFound: true);
        m_Gameplay_ShootGun = m_Gameplay.FindAction("ShootGun", throwIfNotFound: true);
        m_Gameplay_HandMove = m_Gameplay.FindAction("HandMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_GunOpen;
    private readonly InputAction m_Gameplay_ShootGun;
    private readonly InputAction m_Gameplay_HandMove;
    public struct GameplayActions
    {
        private @RightHandActions m_Wrapper;
        public GameplayActions(@RightHandActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @GunOpen => m_Wrapper.m_Gameplay_GunOpen;
        public InputAction @ShootGun => m_Wrapper.m_Gameplay_ShootGun;
        public InputAction @HandMove => m_Wrapper.m_Gameplay_HandMove;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @GunOpen.started += instance.OnGunOpen;
            @GunOpen.performed += instance.OnGunOpen;
            @GunOpen.canceled += instance.OnGunOpen;
            @ShootGun.started += instance.OnShootGun;
            @ShootGun.performed += instance.OnShootGun;
            @ShootGun.canceled += instance.OnShootGun;
            @HandMove.started += instance.OnHandMove;
            @HandMove.performed += instance.OnHandMove;
            @HandMove.canceled += instance.OnHandMove;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @GunOpen.started -= instance.OnGunOpen;
            @GunOpen.performed -= instance.OnGunOpen;
            @GunOpen.canceled -= instance.OnGunOpen;
            @ShootGun.started -= instance.OnShootGun;
            @ShootGun.performed -= instance.OnShootGun;
            @ShootGun.canceled -= instance.OnShootGun;
            @HandMove.started -= instance.OnHandMove;
            @HandMove.performed -= instance.OnHandMove;
            @HandMove.canceled -= instance.OnHandMove;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_keyboardSchemeIndex = -1;
    public InputControlScheme keyboardScheme
    {
        get
        {
            if (m_keyboardSchemeIndex == -1) m_keyboardSchemeIndex = asset.FindControlSchemeIndex("keyboard");
            return asset.controlSchemes[m_keyboardSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnGunOpen(InputAction.CallbackContext context);
        void OnShootGun(InputAction.CallbackContext context);
        void OnHandMove(InputAction.CallbackContext context);
    }
}
